#Q. Create 2 pod definitions.
#Create 2 pod definitions with following features:

#The first pod should be called master and second pod should be called sidecar.
#The second pod should be scheduled to run anywhere the first pod is running i.e. The 2nd pod should run alongside the first pod on the same node.

apiVersion: v1
kind: Pod
metadata:
  name: master
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd            
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
