#Q. Create a service that uses a scratch disk
#Change the service to mount a disk from the host.
#Change the service to mount a persistent volume.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx-2
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
      volumes:
        - name: vol
          hostPath:
            path: /data
            type: Directory
