apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vol-2
  labels:
    app: nginx-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        volumeMounts:
        - mountPath: /vol
          name: vol
        ports:
        - containerPort: 80
      volumes:
        - name: vol
          hostPath:
            path: /data
            type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: my-service-2
spec:
  selector:
    app: nginx-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: my-service-2
