apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2020-05-08T02:00:20Z"
  labels:
    controller-uid: 473fa6a3-405d-4817-976a-675c2e2f4820
    job-name: pi2000
  name: pi2000
  namespace: default
  resourceVersion: "234756"
  selfLink: /apis/batch/v1/namespaces/default/jobs/pi2000
  uid: 473fa6a3-405d-4817-976a-675c2e2f4820
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 473fa6a3-405d-4817-976a-675c2e2f4820
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 473fa6a3-405d-4817-976a-675c2e2f4820
        job-name: pi2000
    spec:
      containers:
      - image: perl
        imagePullPolicy: Always
        name: pi2000
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
