apiVersion: batch/v1
kind: Job
metadata:
  name: job-paralle
spec:
  completions: 20
  parallelism: 5
  template:
    metadata:
      name: job-paralle
    spec:
      containers:
      - name: job
        image: busybox
        command:  ["sh", "-c", "echo 'Hello parallel world' "]
      restartPolicy: Never
